basePath: /api/v1
host: localhost:9191
info:
  contact:
    email: wiliyambhadani@gmail.com
    name: API Support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: glang boiler plate api
  version: "1.0"
paths: {}
schemes:
- http
- https
swagger: "2.0"
