basePath: /api/v1
host: localhost:9191
info:
  contact:
    email: wiliyambhadani@gmail.com
    name: API Support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: glangApi boiler plate
  version: "1.0"
paths:
  /guest/signIn:
    post: {}
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
