basePath: /api/v1
definitions:
  guest.Guest:
    properties:
      err:
        type: string
      message:
        example: some message
        type: string
    type: object
  guest.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:9191
info:
  contact:
    email: wiliyambhadani@gmail.com
    name: API Support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: glang boiler plate api
  version: "1.0"
paths:
  /guest/signIn:
    post:
      consumes:
      - application/json
      description: APi use for login as guest user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/guest.Guest'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/guest.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/guest.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/guest.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/guest.HTTPError'
      summary: guest login api
      tags:
      - guest
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
